spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development

rsa:
  private-key: ${RSA_PRIVATE_KEY:classpath:certs/private.pem}
  public-key: ${RSA_PUBLIC_KEY:classpath:certs/public.pem}

sentry:
  dsn: https://ca078e05dc8e68f551ac2ac6e9f8cf21@o4507102870110208.ingest.de.sentry.io/4507102872666192
  sentry.traces-sample-rate: 1.0
  sentry.exception-resolver-order: -2147483647
